services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PAGEmachine\Searchable\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  PAGEmachine\Searchable\Command\Index\UpdateFullCommand:
    tags:
      - name: console.command
        command: index:update:full

  PAGEmachine\Searchable\Command\Index\UpdatePartialCommand:
    tags:
      - name: console.command
        command: index:update:partial

  PAGEmachine\Searchable\Command\Index\ResetCommand:
    tags:
      - name: console.command
        command: index:reset

  PAGEmachine\Searchable\Command\Index\SetupCommand:
    tags:
      - name: console.command
        command: index:setup


  PAGEmachine\Searchable\DataCollector\TcaDataCollector:
    public: true

  PAGEmachine\Searchable\DataCollector\PagesDataCollector:
    public: true

  PAGEmachine\Searchable\DataCollector\FileDataCollector:
    public: true


  PAGEmachine\Searchable\Preview\DefaultPreviewRenderer:
    public: true

  PAGEmachine\Searchable\Preview\FluidPreviewRenderer:
    public: true

  PAGEmachine\Searchable\Preview\NoPreviewRenderer:
    public: true

  PAGEmachine\Searchable\Preview\PreviewRendererInterface:
    public: true

  PAGEmachine\Searchable\Preview\SimplePreviewRenderer:
    public: true


  PAGEmachine\Searchable\Feature\CompletionSuggestFeature:
    public: true

  PAGEmachine\Searchable\Feature\HighlightFeature:
    public: true

  PAGEmachine\Searchable\Feature\HtmlStripFeature:
    public: true

  PAGEmachine\Searchable\Feature\TermSuggestFeature:
    public: true

  PAGEmachine\Searchable\Query\BulkQuery:
    public: true
