services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PAGEmachine\Searchable\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  PAGEmachine\Searchable\Command\Index\UpdateFullCommand:
    tags:
      - name: console.command
        command: index:update:full

  PAGEmachine\Searchable\Command\Index\UpdatePartialCommand:
    tags:
      - name: console.command
        command: index:update:partial

  PAGEmachine\Searchable\Command\Index\ResetCommand:
    tags:
      - name: console.command
        command: index:reset

  PAGEmachine\Searchable\Command\Index\SetupCommand:
    tags:
      - name: console.command
        command: index:setup

  PAGEmachine\Searchable\Hook\DynamicFlexFormHook:
    tags:
      - name: event.listener
        identifier: 'pagemachine/searchable/modify-data-structure'
        method: 'modifyDataStructure'

  PAGEmachine\Searchable\Service\IndexingService:
    public: true

  PAGEmachine\Searchable\Domain\Repository\UpdateQueue:
    public: true

  PAGEmachine\Searchable\DataCollector\TCA\FormDataRecord:
    autowire: false
